// frontend/nuxt/app/pages/register.vue
<script setup lang="ts">
import type { FetchError } from '~/utils/types'

const username = ref('')
const email = ref('')
const fullName = ref('')
const role = ref<'Volunteer' | 'Event Manager'>('Volunteer')
const password = ref('')
const confirmPassword = ref('')
const router = useRouter()

const showErrorMessage = ref(false)
const errorMessage = ref('')

const onSubmit = async () => {
  if (password.value !== confirmPassword.value) {
    showErrorMessage.value = true
    errorMessage.value = 'Password do not match!'
  }
  try {
    await $fetch('/api/register', {
      method: 'POST',
      body: {
        userRole: role.value,
        username: username.value,
        email: email.value,
        password: password.value,
        fullName: fullName.value
      }
    })
    router.push('/login')
  } catch (error) {
    const err = error as FetchError
    showErrorMessage.value = true
    errorMessage.value = err.data.err.message ?? 'Unexpected error during registration'
  }
}
</script>

<template>
  <div class="min-h-screen bg-gray-100 font-sans text-gray-800">
    <header class="h-16 bg-[#256EB1] text-white shadow-md">
      <div class="h-full px-6 flex items-center justify-between">
        <div class="flex items-center space-x-2">
          <img class="w-6 h-6 rounded-md bg-transparent shadow-inner" src="../../../favicon.png" />
          <router-link to="/register" class="text-sm text-white">
            <span class="text-xl font-medium">VolunteerHub</span>
          </router-link>
        </div>
        <router-link to="/login" class="text-sm text-white">
          <button
            type="button"
            class="bg-transparent text-white font-semibold text-[1.1rem] px-4 py-2 rounded-md hover:bg-[#ffffff33] hover:cursor-pointer transition duration-300 ease-in-out hover:-translate-y-px hover:shadow-md"
          >
            Log In
          </button>
        </router-link>
      </div>
    </header>

    <main class="max-w-[600px] mx-auto py-16 px-4">
      <section class="bg-white p-8 rounded-xl shadow-lg">
        <h1 class="text-4xl mb-6">Sign Up</h1>

        <form class="space-y-6" @submit.prevent="onSubmit">
          <!-- username + email on one row -->
          <div class="flex gap-4">
            <div class="flex-1">
              <label for="username" class="text-[1.1rem] text-gray-700">Username</label>
              <input
                id="username"
                v-model="username"
                type="text"
                class="w-full h-10 px-4 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600"
                autocomplete="username"
                required
              />
            </div>

            <div class="flex-1">
              <label for="email" class="text-[1.1rem] text-gray-700">Email</label>
              <input
                id="email"
                v-model="email"
                type="text"
                class="w-full h-10 px-4 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600"
                autocomplete="email"
                required
              />
            </div>
          </div>

          <!-- fullName -->
          <div class="flex gap-4">
            <div class="flex-1">
              <label for="fullName" class="text-[1.1rem] text-gray-700">Full Name</label>
              <input
                id="fullName"
                v-model="fullName"
                type="text"
                class="w-full h-10 px-4 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600"
                autocomplete="given-name"
                required
              />
            </div>
          </div>

          <div>
            <label for="role" class="text-[1.1rem] text-gray-700">User Role</label>
            <select
              id="role"
              v-model="role"
              class="w-full h-10 px-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600 text-[1rem]"
              required
            >
              <option value="Volunteer">Volunteer</option>
              <option value="Event Manager">Event Manager</option>
            </select>
          </div>

          <div>
            <label for="password" class="text-[1.1rem] text-gray-700">Password</label>
            <input
              id="password"
              v-model="password"
              type="password"
              class="w-full h-10 px-4 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600"
              autocomplete="new-password"
              required
            />
          </div>

          <div>
            <label for="confirmPassword" class="text-[1.1rem] text-gray-700">Confirm Password</label>
            <input
              id="confirmPassword"
              v-model="confirmPassword"
              type="password"
              class="w-full h-10 px-4 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-600"
              autocomplete="new-password"
              required
            />
          </div>

          <div class="flex justify-between items-center">
            <router-link to="/login" class="text-[1.1rem] text-blue-600 hover:underline"
              >Already have an account? Log In</router-link
            >
          </div>

          <div v-if="showErrorMessage" class="text-[1.1rem] text-red-600 mt-2">
            {{ errorMessage }}
          </div>

          <div class="flex justify-end">
            <button
              type="submit"
              class="bg-[#256EB1] text-white text-[1.2rem] px-6 py-2 rounded-md font-medium hover:bg-[#2379B8] hover:cursor-pointer transition duration-300 ease-in-out hover:-translate-y-px hover:shadow-md"
            >
              Sign Up
            </button>
          </div>
        </form>
      </section>
    </main>
  </div>
</template>

// frontend/sveltekit-minimal/src/routes/register/+page.svelte
<script lang="ts">
  import type { PageData } from "$types";

  let { data, form } = $props() satisfies {
    data: PageData,
    form: {
      errors: string[],
      data: {
        userRole: string,
        username: string,
        email: string,
        password: string,
        fullName: string,
      },
    },
  };
</script>

<h1>register!</h1>

<form method="POST">
  <label for="user-role">user-role</label>
  <select name="user-role" required>
    <option value="volunteer">volunteer</option>
    <option value="event-manager">event-manager</option>
    <option value="administrator">administrator</option>
  </select>

  <label for="username">username</label>
  <input type="text" name="username" value={form?.data.username ?? ""} required>

  <label for="email">email</label>
  <input type="text" name="email" value={form?.data.email ?? ""} required>

  <label for="password">password</label>
  <input type="password" name="password" value={form?.data.password ?? ""} required>

  <label for="full-name">full-name</label>
  <input type="text" name="full-name" value={form?.data.fullName ?? ""} required>

  <button type="submit">register</button>
</form>

{#each form?.errors as error}
  <p style="color: red;">{error.message}</p>
{/each}
